import {
  Globe,
  Smartphone,
  Webhook,
  Gauge,
  Eye,
  PackageCheck,
  Keyboard,
  FileText,
  CheckSquare,
  Tag,
  Boxes,
  MessageSquare,
  Database,
  Workflow,
  BellRing,
  Clock,
  ShieldCheck,
  Send,
  ArrowUpCircle,
  CalendarClock,
  Server,
  Sparkles,
  Infinity as InfinityIcon,
  type LucideIcon,
} from "lucide-react";

export const capabilityIcons: Record<string, LucideIcon> = {
  "Web automation": Globe,
  "App automation": Smartphone,
  "API automation": Webhook,
  "Performance & load testing": Gauge,
  "Manual QA": Eye,
  "Order & inventory reconciliation": PackageCheck,
  "Repetitive data entry": Keyboard,
  "Scheduled report generation": FileText,
  "Rule-based approvals": CheckSquare,
  "Competitor price tracking": Tag,
  "Stock & MRP monitoring": Boxes,
  "Review monitoring": MessageSquare,
  "Structured delivery": Database,
  "Cross-system workflows": Workflow,
  "Notification & escalation chains": BellRing,
  "Scheduled batch jobs": Clock,
  "Confirmed, not raw": ShieldCheck,
  "Delivered where you work": Send,
  "Escalation on silence": ArrowUpCircle,
  "Scheduled execution": CalendarClock,
  "Production, not staging": Server,
  "Always on": InfinityIcon,
};

export function getCapabilityIcon(title: string): LucideIcon {
  return capabilityIcons[title] ?? Sparkles;
}